-- Выполнить один раз в Supabase: Project -> SQL Editor -> New query -> вставить и Run

create table if not exists public.workout_logs (
  id bigint primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  type text not null,
  body_weight numeric,
  sleep numeric,
  feeling int,
  finisher text,
  notes text,
  sets jsonb,
  created_at timestamptz default now()
);
alter table public.workout_logs enable row level security;
create policy "workout_logs_own" on public.workout_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.checkins (
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  weight numeric,
  sleep numeric,
  feeling int,
  note text,
  primary key (user_id, date)
);
alter table public.checkins enable row level security;
create policy "checkins_own" on public.checkins
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.cooper_tests (
  user_id uuid not null references auth.users(id) on delete cascade,
  week int not null,
  distance int not null,
  primary key (user_id, week)
);
alter table public.cooper_tests enable row level security;
create policy "cooper_tests_own" on public.cooper_tests
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.strength_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  ex text not null,
  kg numeric not null
);
alter table public.strength_records enable row level security;
create policy "strength_records_own" on public.strength_records
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.schedule_overrides (
  user_id uuid not null references auth.users(id) on delete cascade,
  week int not null,
  data jsonb not null,
  primary key (user_id, week)
);
alter table public.schedule_overrides enable row level security;
create policy "schedule_overrides_own" on public.schedule_overrides
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
